public enum GameStateEnum
{
  IDLE_WAITING,
  ONE_HAND_WAITING,
  TWO_HANDS_WAITING,
  CLOSE_HAND_WAITING,
  READY_STARTING,
  SET_STARTING,
  GO_STARTING,
  PLAYING,
  WINNER_PLAYER_LEFT,
  WINNER_PLAYER_RIGHT
}